# https://vuepress.vuejs.org/guide/deploy.html#github-pages

language: node_js

node_js:
  - '10'

install:
  - npm i -g vuepress

script:
  - npm run build

#cache:
#  directories:
#    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs
  repo: nekohack
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
